config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  get 'home/index'
  get 'home/dashboard'

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
           

  #need validation so i cant add overlapping meetings

    # save duration and overtime as an integer 
    before_save :set_duration
      before_save :daily_total_ot

     # calculate duration which is meeting end time minus meeting start time 
    def set_duration
        self.duration = (end_date - start_date).to_i
    end

    # method to add total duration for each day 
  def self.daily_total_duration(date)
    Meeting.where("start_date >= ? AND end_date < ?", date.beginning_of_day, date.end_of_day).sum(:duration)
  end

   #calculate total overtime for each day 
    def daily_total_ot
      self.overtime = Meeting.where("start_date >= ? AND end_date < ?", self.start_date.beginning_of_day, self.start_date.end_of_day).sum(:duration) - 26700.to_i
   
     end

   # method for total overtime altogether


   # method for total overtime between flexi period months 

   # bootstrap progress bar for a flexi day 
   #n ot finished yet
   def duration_percent
    duration / 24.hours.to_f * 100
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @meetings = Meeting.order(start_date: :asc)
   # @meetings = Meeting.all
    
  end

      def dashboard
        @meetings = Meeting.order(start_date: :asc)
      # @meetings = Meeting.all
        
      end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_date, :end_date, :duration, :overtime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/home/dashboard.html.erb
<div class="mw-90">
<h1>Meetings</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Start date</th>
     <th>End date</th>
      <th>Duration</th>
      <th>Duration Time</th>
    </tr>
  </thead>

  <tbody>
  <% @meetings.pluck("start_date").map{ |x| x.to_date}.sort.uniq.each do | date | %>
  <tr>
   <td> <%= date.strftime("%d-%b-%Y") %> </td>
   <td><h3>Total Overtime</h3></td>
   

  </tr>
    <% @meetings.where(start_date: (date.to_time)..date.to_time+86399).each do | meeting | %>
      <tr>
        <td><% meeting.name %></td>
        <td><% meeting.start_date.strftime("%d-%b-%Y %I:%M %p") %></td>
        <td><% meeting.end_date.strftime("%d-%b-%Y %I:%M %p") %></td>
        <td><%= meeting.duration %></td>
       
        
       <% if  (meeting.daily_total_ot) > 26700 %>
       <td><%= Time.at(meeting.daily_total_ot).utc.strftime("%H hours and %M minutes ") %></td>
        <% else  %>
       <td>No Overtime</td>
       <% end %>
      </tr>
    <% end %>
  </tbody>
  <% end %>
</table>
<br><br>

<% @meetings.each do |meeting| %>
<% if (meeting.daily_total_ot - 26700) > 0 %>
<div class="progress"><br>
  <div class="progress-bar bg-success" role="progressbar" style="width: <%= meeting.duration_percent %>%;" aria-valuenow="<%= meeting.duration_percent %>" aria-valuemin="0" aria-valuemax="100"><%= Time.at(meeting.daily_total_ot - 26700).utc.strftime("%H hours and %M minutes ") %>%</div>
  <br>
</div>
<br>
<% end %>

<% end %>
<br>


</div>

app/views/home/index.html.erb
<div class="text-center"S>
<h1 class="text-align center">My Time App</h1>
<h2><%= Time.now.strftime("%d-%b-%Y %I:%M %p") %></h2>
</div>

<div class="mw-90">
<%= month_calendar(attribute: :start_date, events: @meetings) do |date, meetings| %>
<%= date %>

<% meetings.each do |meeting| %>
  <div>
  
   <button type="button" class="btn btn-success">
    <%= meeting.start_date.strftime("%d-%b-%Y %I:%M %p") %>
  </button> 
  <button type="button" class="btn btn-danger">
    <%= meeting.end_date.strftime("%d-%b-%Y %I:%M %p") %></button>
  </div>
<% end %>
<% if Meeting.daily_total_duration(date) > 0 %>
<button type="button" class="btn btn-warning" ><%= Time.at(Meeting.daily_total_duration(date)).utc.strftime("%H hrs & %M mins ") %></button>

<% end  %>
<% end %>
  
</div>
</div>
<div class="mw-90">
<h1>Meetings</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Start date</th>
      <th scope="col">End date</th>
      <th scope="col">Duration</th>
      <th scope="col">Overtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.start_date.strftime("%d-%b-%Y") %></td>
        <td><%= meeting.start_date.strftime("%I:%M %p") %></td>
        <td><%= meeting.end_date.strftime("%I:%M %p")  %></td>
        <td><%= Time.at(meeting.duration).utc.strftime("%H hours and %M minutes ") %></td>
        <% if  (meeting.daily_total_ot) > 0 %>
        <td><%= Time.at(meeting.daily_total_ot).utc.strftime("%H hours and %M minutes ") %></td>
         <% else  %>
        <td>No Overtime</td>
        <% end %>
      
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mytimeapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<div >
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">MyTimeApp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "Home", root_path %>
        </li>
        <li class="nav-item">
          <%= link_to "My Dashboard", home_dashboard_path %>
         
        </li>
        
        <li class="nav-item">
          <%= link_to "Meeting", meetings_path %>
        </li>
      </ul>
    </div>
  </nav>

</div>
    <%= yield %>
 
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>

  <div class="field">
    <% form.label :duration %>
    <% form.number_field :duration %>
  </div>

  <div class="field">
    <% form.label :overtime %>
    <% form.number_field :overtime %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Duration</th>
   
      <th>Overtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.start_date %></td>
        <td><%= meeting.end_date %></td>
        <td><%= meeting.duration %></td>
       
        <td><%= meeting.overtime %></td>
        
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @meeting.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @meeting.end_date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @meeting.duration %>
</p>

<p>
  <strong>Overtime:</strong>
  <%= @meeting.overtime %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>